//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mecenat_GSB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSOCIATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSOCIATION()
        {
            this.CONTRAT_D_AIDE = new HashSet<CONTRAT_D_AIDE>();
            this.TRACEINTERVENTION = new HashSet<TRACEINTERVENTION>();
        }
    
        public short NUM_ASSOCIATION { get; set; }
        public short NUM_PAYS { get; set; }
        public short NUM_MISSION { get; set; }
        public string NOM_ASSOCIATION { get; set; }
        public string NOM_RESPONSABLE_ASSOCIATION { get; set; }
    
        public virtual MISSION MISSION { get; set; }
        public virtual PAYS PAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAT_D_AIDE> CONTRAT_D_AIDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACEINTERVENTION> TRACEINTERVENTION { get; set; }
    }
}
