//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mecenat_GSB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECENAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MECENAT()
        {
            this.CONTRAT_D_AIDE = new HashSet<CONTRAT_D_AIDE>();
            this.TRACEINTERVENTION = new HashSet<TRACEINTERVENTION>();
        }
    
        public short NUM_MECENAT { get; set; }
        public short NUM_PAYS { get; set; }
        public string LIBELLE_MECENAT { get; set; }
        public Nullable<System.DateTime> DATE_PROPOSITION { get; set; }
        public Nullable<System.DateTime> DATE_RETENUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAT_D_AIDE> CONTRAT_D_AIDE { get; set; }
        public virtual PAYS PAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACEINTERVENTION> TRACEINTERVENTION { get; set; }
    }
}
