//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mecenat_GSB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDD_MECENATEntities1 : DbContext
    {
        public BDD_MECENATEntities1()
            : base("name=BDD_MECENATEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASSOCIATION> ASSOCIATION { get; set; }
        public virtual DbSet<CONTRAT_D_AIDE> CONTRAT_D_AIDE { get; set; }
        public virtual DbSet<MECENAT> MECENAT { get; set; }
        public virtual DbSet<MISSION> MISSION { get; set; }
        public virtual DbSet<PAYS> PAYS { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<TRACEINTERVENTION> TRACEINTERVENTION { get; set; }
        public virtual DbSet<UTILISATEUR> UTILISATEUR { get; set; }
    }
}
