//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mecenat_GSB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACEINTERVENTION
    {
        public short NUM_INTERVENTION { get; set; }
        public Nullable<short> NUM_MECENAT { get; set; }
        public Nullable<short> NUM_ASSOCIATION { get; set; }
        public Nullable<short> NUM_CONTRAT { get; set; }
        public short NUM_UTILISATEUR { get; set; }
        public string OPERATION_REALISEE { get; set; }
        public Nullable<System.DateTime> DATE_INTERVENTION { get; set; }
        public Nullable<System.DateTime> HEURE_INTERVENTION { get; set; }
    
        public virtual ASSOCIATION ASSOCIATION { get; set; }
        public virtual CONTRAT_D_AIDE CONTRAT_D_AIDE { get; set; }
        public virtual MECENAT MECENAT { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
