//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mecenat_GSB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILISATEUR()
        {
            this.TRACEINTERVENTION = new HashSet<TRACEINTERVENTION>();
        }
    
        public short NUM_UTILISATEUR { get; set; }
        public short NUM_SERVICE { get; set; }
        public string NOM_UTILISATEUR { get; set; }
        public string PRENOM_UTILISATEUR { get; set; }
        public string ROLE_UTILISATEUR { get; set; }
        public string LOGIN_UTILISATEUR { get; set; }
        public string MDP_UTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATE_DERNIERE_MODIF_MDP { get; set; }
    
        public virtual SERVICE SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACEINTERVENTION> TRACEINTERVENTION { get; set; }
    }
}
